create table tb_ordem (id int8 generated by default as identity, endereco varchar(255), latitude float8, longitude float8, momento timestamp, status int4, total float8, primary key (id));
create table tb_ordem_pedido (ordem_id int8 not null, produto_id int8 not null, primary key (ordem_id, produto_id));
create table tb_produto (id int8 generated by default as identity, descricao varchar(255), image_uri varchar(255), nome varchar(255), preco float8, primary key (id));
alter table if exists tb_ordem_pedido add constraint FKahafcdgxipcookcx45uognx89 foreign key (produto_id) references tb_produto;
alter table if exists tb_ordem_pedido add constraint FKhagsh87xn4nfbndreicne4j3l foreign key (ordem_id) references tb_ordem;
